name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2

      - name: Publish Docs
        run: |
          COMMIT_DATE_EPOCH="$(git log -1 --pretty=%ct)"
          COMMIT_DATE="$(date -d"@${COMMIT_DATE_EPOCH}" --iso-8601=seconds)"

          tmpdir="$(mktemp -d)"
          docroot="${tmpdir}/doc"
          mv "doc/build/html" "${docroot}"
          pushd "${docroot}"
          touch .nojekyll

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global init.defaultBranch master
          git init
          git remote add deploy "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git"
          git checkout -b gh-pages
          git add .
          msg="Updating Docs for commit ${{ github.sha }} made on ${COMMIT_DATE} from ${{ github.ref }} by ${{ github.actor }}"
          git commit -m "${msg}"
          git push deploy gh-pages --force

          popd
